name: Code Style

on: [ push, pull_request ]

jobs:
    fix:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2
                
            -   name: Code style check
                uses: TheDragonCode/codestyler@v3
                if: ${{ github.event_name == 'pull_request' }}
                

            -   name: Code style fix
                uses: TheDragonCode/codestyler@v3
                if: ${{ github.ref == 'refs/heads/dev' }}
                with:
                    # This token uses GitHub Actions to execute code.
                    # Required when `fix` is `true`.
                    # The default value is `${{ secrets.GITHUB_TOKEN }}`.
                    github_token: ${{ secrets.GITHUB_TOKEN }}

                    # Activates the mode of accepting changes with the creation
                    # of commits.
                    fix: true

                    # Activates the actualization of the `.editorconfig` file.
                    # Works only when the `fix` option is enabled.
                    # By default, true
                    editorconfig: true

                    # Activates Dependabot file processing.
                    # Works only when the `fix` option is enabled.
                    # By default, true
                    dependabot: true

                    # Normalizing `composer.json`.
                    # Works only when the `fix` option is enabled.
                    # By default, true
                    normalize: true

                    # Increase the verbosity of messages for debug
                    # By default, false
                    verbose: true
